# Generated by Django 5.2.6 on 2025-10-23 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Identificación')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('marital_status', models.CharField(choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('D', 'Divorciado/a'), ('V', 'Viudo/a')], max_length=1, verbose_name='Estado Civil')),
                ('occupation', models.CharField(max_length=100, verbose_name='Ocupación')),
                ('insurance_provider', models.CharField(blank=True, max_length=100, verbose_name='Proveedor de Seguro')),
                ('insurance_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Seguro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='patients_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
